name: Build and push docker image to Docker Hub

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Java CI with Maven" ]
    branches: [ master ]
    types:
      - completed
  push:
    tags:
      - 'v*'

jobs:
  build:
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven

      - name: Set version
        if: ${{ github.event_name == 'push' && startsWith(github.ref_name, 'v') }}
        run: mvn -B clean versions:set -DnewVersion=${GITHUB_REF_NAME#"v"}

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -DskipTests

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: kotoant/spring-petclinic-rest
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
